# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('die_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dice.DieSet')),
            ],
        ),
    ]
