# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dice', '0001_initial'),
        ('actors', '0001_initial'),
        ('spells', '0001_initial'),
        ('affects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('poison_damage', models.PositiveSmallIntegerField(default=0)),
                ('fire_damage', models.PositiveSmallIntegerField(default=0)),
                ('cold_damage', models.PositiveSmallIntegerField(default=0)),
                ('acid_damage', models.PositiveSmallIntegerField(default=0)),
                ('electricity_damage', models.PositiveSmallIntegerField(default=0)),
                ('value', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('for_sale', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
                ('armor_class', models.PositiveSmallIntegerField(default=0)),
                ('armor_type', models.CharField(choices=[('Helmet', 'Helmet'), ('Cloak', 'Cloak'), ('Armor', 'Armor'), ('Shoes', 'Shoes'), ('Gloves', 'Gloves'), ('Pants', 'Pants')], db_index=True, default='Armor', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
                ('jewelry_type', models.CharField(choices=[('Ring', 'Ring'), ('Necklace', 'Necklace'), ('Crown', 'Crown')], db_index=True, default='Ring', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Missile',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
                ('missile_type', models.CharField(choices=[('Arrow', 'Arrow'), ('Bolt', 'Bolt'), ('Stone', 'Stone')], db_index=True, default='Arrow', max_length=10)),
                ('usable_weapon_type', models.CharField(choices=[('Bow', 'Bow'), ('Crossbow', 'Crossbow'), ('Sling', 'Sling')], db_index=True, default='Arrow', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
                ('min_level', models.PositiveSmallIntegerField(default=0)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrolls', to='spells.Spell')),
            ],
            options={
                'abstract': False,
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
                ('two_handed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('items.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='die_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dice.DieSet'),
        ),
        migrations.AddField(
            model_name='item',
            name='hit_affects',
            field=models.ManyToManyField(blank=True, related_name='item_hit_affects', to='affects.Affect'),
        ),
        migrations.AddField(
            model_name='item',
            name='holder_affects',
            field=models.ManyToManyField(blank=True, related_name='item_holder_affects', to='affects.Affect'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='actors.Actor'),
        ),
        migrations.CreateModel(
            name='MissileWeapon',
            fields=[
                ('weapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Weapon')),
                ('missile_type', models.CharField(choices=[('Bow', 'Bow'), ('Crossbow', 'Crossbow'), ('Sling', 'Sling')], db_index=True, default='Bow', max_length=10)),
                ('missile_range', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('items.weapon',),
        ),
    ]
