# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20170409_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='game_map_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
