# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('affect_turns', models.PositiveSmallIntegerField(default=0)),
                ('affect_turns_remaining', models.PositiveSmallIntegerField(default=0)),
                ('permanent', models.BooleanField(default=False)),
                ('curse', models.BooleanField(default=False)),
                ('affect_type', models.CharField(choices=[(0, 'Add'), (1, 'Multiply')], db_index=True, default=0, max_length=10)),
                ('modifier', models.FloatField(default=0)),
                ('attribute', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
