# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('affect_turns', models.PositiveSmallIntegerField()),
                ('affect_turns_remaining', models.PositiveSmallIntegerField()),
                ('permanent', models.BooleanField(default=False)),
                ('curse', models.BooleanField(default=False)),
                ('modifier', models.SmallIntegerField()),
                ('attribute', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
