# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affect',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='affect',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='affect',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
