# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affect',
            name='affect_turns',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affect',
            name='affect_turns_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affect',
            name='modifier',
            field=models.SmallIntegerField(default=0),
        ),
    ]
