# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('game_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemap',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Location'),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemap',
            name='slug',
            field=models.SlugField(default='sdflj'),
            preserve_default=False,
        ),
    ]
