# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_map', '0002_auto_20170409_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='game_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_map.GameMap'),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
