# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('game_map', '0004_auto_20170409_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemap',
            name='bottom_left',
        ),
        migrations.RemoveField(
            model_name='gamemap',
            name='bottom_right',
        ),
        migrations.RemoveField(
            model_name='gamemap',
            name='top_left',
        ),
        migrations.RemoveField(
            model_name='gamemap',
            name='top_right',
        ),
        migrations.AddField(
            model_name='gamemap',
            name='origin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_map_origin_location', to='base.Location'),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='populate_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
