# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_auto_20171211_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='display_char',
            field=models.CharField(default='k', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monstertype',
            name='display_char',
            field=models.CharField(default='k', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monster',
            name='map_level',
            field=models.PositiveSmallIntegerField(default=1, help_text="Current location of the game object. Necessary if a map wasn't already associated with this object, one is created based on this."),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='map_level',
            field=models.PositiveSmallIntegerField(default=1, help_text="Current location of the game object. Necessary if a map wasn't already associated with this object, one is created based on this."),
        ),
    ]
