# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affects', '0002_auto_20170312_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('base_strength', models.PositiveSmallIntegerField(default=10)),
                ('base_dexterity', models.PositiveSmallIntegerField(default=10)),
                ('base_constitution', models.PositiveSmallIntegerField(default=10)),
                ('base_intelligence', models.PositiveSmallIntegerField(default=10)),
                ('base_wisdom', models.PositiveSmallIntegerField(default=10)),
                ('base_charisma', models.PositiveSmallIntegerField(default=10)),
                ('base_poison_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_fire_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_cold_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_acid_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_electricity_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_level', models.PositiveSmallIntegerField(default=1)),
                ('base_hp', models.PositiveSmallIntegerField(default=10)),
                ('base_mana', models.PositiveSmallIntegerField(default=10)),
                ('base_armor_class', models.PositiveSmallIntegerField(default=10)),
                ('base_max_carry_weight', models.PositiveSmallIntegerField(default=0)),
                ('strength', models.PositiveSmallIntegerField(default=10)),
                ('dexterity', models.PositiveSmallIntegerField(default=10)),
                ('constitution', models.PositiveSmallIntegerField(default=10)),
                ('intelligence', models.PositiveSmallIntegerField(default=10)),
                ('wisdom', models.PositiveSmallIntegerField(default=10)),
                ('charisma', models.PositiveSmallIntegerField(default=10)),
                ('poison_resist', models.PositiveSmallIntegerField(default=10)),
                ('fire_resist', models.PositiveSmallIntegerField(default=10)),
                ('cold_resist', models.PositiveSmallIntegerField(default=10)),
                ('acid_resist', models.PositiveSmallIntegerField(default=10)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('hp', models.PositiveSmallIntegerField(default=10)),
                ('hp_max', models.PositiveSmallIntegerField(default=10)),
                ('mana', models.PositiveSmallIntegerField(default=10)),
                ('mana_max', models.PositiveSmallIntegerField(default=10)),
                ('armor_class', models.PositiveSmallIntegerField(default=10)),
                ('max_carry_weight', models.PositiveSmallIntegerField(default=0)),
                ('current_carry_weight', models.PositiveSmallIntegerField(default=0)),
                ('poison_attack_damage', models.PositiveSmallIntegerField(default=0)),
                ('fire_attack_damage', models.PositiveSmallIntegerField(default=0)),
                ('cold_attack_damage', models.PositiveSmallIntegerField(default=0)),
                ('acid_attack_damage', models.PositiveSmallIntegerField(default=0)),
                ('electricity_attack_damage', models.PositiveSmallIntegerField(default=0)),
                ('experience_earned', models.PositiveIntegerField(default=0)),
                ('experience_to_level', models.PositiveIntegerField(default=0)),
                ('experience_value', models.PositiveIntegerField(default=10)),
                ('sleeping', models.BooleanField(default=False)),
                ('affects', models.ManyToManyField(blank=True, related_name='actor_affects', to='affects.Affect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='actors.Actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('affects', models.ManyToManyField(blank=True, related_name='race_affects', to='affects.Affect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
