# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('strength', models.PositiveSmallIntegerField()),
                ('dexterity', models.PositiveSmallIntegerField()),
                ('constitution', models.PositiveSmallIntegerField()),
                ('intelligence', models.PositiveSmallIntegerField()),
                ('wisdom', models.PositiveSmallIntegerField()),
                ('charisma', models.PositiveSmallIntegerField()),
                ('level', models.PositiveSmallIntegerField()),
                ('hp', models.PositiveSmallIntegerField()),
                ('mana', models.PositiveSmallIntegerField()),
                ('armor_class', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
