# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('spells', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='actor_inventory', to='items.Item'),
        ),
        migrations.AddField(
            model_name='actor',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='actor_spells', to='spells.Spell'),
        ),
        migrations.AddField(
            model_name='actor',
            name='wearing',
            field=models.ManyToManyField(blank=True, related_name='actor_armor', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='wielding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_weapon', to='items.Weapon'),
        ),
    ]
