# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('spells', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='armor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_armor', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='cloak',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_cloak', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='gloves',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_gloves', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='helmet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_helmet', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='actor_inventory', to='items.Item'),
        ),
        migrations.AddField(
            model_name='actor',
            name='pants',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_pants', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='quiver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='items.Missile'),
        ),
        migrations.AddField(
            model_name='actor',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='actors.Race'),
        ),
        migrations.AddField(
            model_name='actor',
            name='range_weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='items.MissileWeapon'),
        ),
        migrations.AddField(
            model_name='actor',
            name='shield',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_shield', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='shoes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_shoes', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='actor_spells', to='spells.Spell'),
        ),
        migrations.AddField(
            model_name='actor',
            name='weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_weapon', to='items.Weapon'),
        ),
    ]
