# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20170312_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='acid_attack_damage',
            new_name='damage_bonus_acid',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='cold_attack_damage',
            new_name='damage_bonus_cold',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='electricity_attack_damage',
            new_name='damage_bonus_electricity',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='fire_attack_damage',
            new_name='damage_bonus_fire',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='poison_attack_damage',
            new_name='damage_bonus_poison',
        ),
        migrations.AddField(
            model_name='actor',
            name='damage_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
