# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20170314_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='damage_bonus',
            new_name='damage_bonus_melee',
        ),
        migrations.AddField(
            model_name='actor',
            name='damage_bonus_range',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actor',
            name='electricity_resist',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
