# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 04:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actors', '0004_auto_20170324_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL),
        ),
    ]
