# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0009_auto_20170409_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='game_map_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
