# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affects', '0005_auto_20170409_2204'),
        ('actors', '0010_actor_game_map_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('affects', models.ManyToManyField(blank=True, related_name='class_affects', to='affects.Affect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
