# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0011_actorclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_class', to='actors.ActorClass'),
        ),
    ]
