# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
        ('game_map', '0001_initial'),
        ('affects', '0001_initial'),
        ('base', '0001_initial'),
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('affects', models.ManyToManyField(blank=True, related_name='class_affects', to='affects.Affect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('base_strength', models.PositiveSmallIntegerField(default=10)),
                ('base_dexterity', models.PositiveSmallIntegerField(default=10)),
                ('base_constitution', models.PositiveSmallIntegerField(default=10)),
                ('base_intelligence', models.PositiveSmallIntegerField(default=10)),
                ('base_wisdom', models.PositiveSmallIntegerField(default=10)),
                ('base_charisma', models.PositiveSmallIntegerField(default=10)),
                ('base_poison_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_fire_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_cold_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_acid_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_electricity_resist', models.PositiveSmallIntegerField(default=10)),
                ('base_level', models.PositiveSmallIntegerField(default=1)),
                ('base_hp', models.PositiveSmallIntegerField(default=10)),
                ('base_mana', models.PositiveSmallIntegerField(default=10)),
                ('base_armor_class', models.PositiveSmallIntegerField(default=10)),
                ('base_max_carry_weight', models.PositiveSmallIntegerField(default=0)),
                ('strength', models.PositiveSmallIntegerField(default=10)),
                ('dexterity', models.PositiveSmallIntegerField(default=10)),
                ('constitution', models.PositiveSmallIntegerField(default=10)),
                ('intelligence', models.PositiveSmallIntegerField(default=10)),
                ('wisdom', models.PositiveSmallIntegerField(default=10)),
                ('charisma', models.PositiveSmallIntegerField(default=10)),
                ('poison_resist', models.PositiveSmallIntegerField(default=10)),
                ('fire_resist', models.PositiveSmallIntegerField(default=10)),
                ('cold_resist', models.PositiveSmallIntegerField(default=10)),
                ('acid_resist', models.PositiveSmallIntegerField(default=10)),
                ('electricity_resist', models.PositiveSmallIntegerField(default=10)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('hp', models.PositiveSmallIntegerField(default=10)),
                ('hp_max', models.PositiveSmallIntegerField(default=10)),
                ('mana', models.PositiveSmallIntegerField(default=10)),
                ('mana_max', models.PositiveSmallIntegerField(default=10)),
                ('armor_class', models.PositiveSmallIntegerField(default=10)),
                ('max_carry_weight', models.PositiveSmallIntegerField(default=0)),
                ('current_carry_weight', models.PositiveSmallIntegerField(default=0)),
                ('damage_bonus_melee', models.PositiveSmallIntegerField(default=0)),
                ('damage_bonus_range', models.PositiveSmallIntegerField(default=0)),
                ('damage_bonus_poison', models.PositiveSmallIntegerField(default=0)),
                ('damage_bonus_fire', models.PositiveSmallIntegerField(default=0)),
                ('damage_bonus_cold', models.PositiveSmallIntegerField(default=0)),
                ('damage_bonus_acid', models.PositiveSmallIntegerField(default=0)),
                ('damage_bonus_electricity', models.PositiveSmallIntegerField(default=0)),
                ('experience_earned', models.PositiveIntegerField(default=0)),
                ('experience_to_level', models.PositiveIntegerField(default=0)),
                ('experience_value', models.PositiveIntegerField(default=10)),
                ('sleeping', models.BooleanField(default=False)),
                ('actor_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_class', to='players.Class')),
                ('affects', models.ManyToManyField(blank=True, related_name='player_affects', to='affects.Affect')),
                ('armor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_armor', to='items.Armor')),
                ('cloak', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_cloak', to='items.Armor')),
                ('game_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_map.GameMap')),
                ('gloves', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_gloves', to='items.Armor')),
                ('helmet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_helmet', to='items.Armor')),
                ('inventory', models.ManyToManyField(blank=True, related_name='player_inventory', to='items.Item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to=settings.AUTH_USER_MODEL)),
                ('pants', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_pants', to='items.Armor')),
                ('quiver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='items.Missile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='players.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('affects', models.ManyToManyField(blank=True, related_name='race_affects', to='affects.Affect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='players.Race'),
        ),
        migrations.AddField(
            model_name='player',
            name='range_weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='items.MissileWeapon'),
        ),
        migrations.AddField(
            model_name='player',
            name='shield',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_shield', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='player',
            name='shoes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_shoes', to='items.Armor'),
        ),
        migrations.AddField(
            model_name='player',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='player_spells', to='spells.Spell'),
        ),
        migrations.AddField(
            model_name='player',
            name='weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_weapon', to='items.Weapon'),
        ),
    ]
