# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='map_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current location of the game object. Necessary.'),
        ),
    ]
