# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20171217_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tohit_bonus_melee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='tohit_bonus_range',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
